### PR TITLE
add erlang 20 and 21 for test

### PR DESCRIPTION
**Pull request by getong**

### CODE REVIEW

**Comment by uwiger** [comment]
Am I right in assuming that this test failure is caused by the exometer_core version not yet having been updated for Erlang 19?
https://github.com/Feuerlabs/exometer_core/pull/94

**Comment by getong** [comment]
@uwiger A new tag is needed in exometer_core. Or I just use the master branch?

**Comment by uwiger** [comment]
I've been going through outstanding PRs on exometer_core and merging most of them. My plan was to make a new tag once I'm finished with that and it seems to work.

**Comment by getong** [comment]
wait for Feuerlabs/exometer_core#114

**Comment by Argonus** [comment]
@uwiger Hi, any updates on this?

**Comment by getong** [comment]
@tolbrino 
Do you have time to review the code?

**Pull request closed without merging**
